clinic-management/clinic-management/Models/PCollege.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCollege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCollege()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int CollegeID { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}

clinic-management/clinic-management/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{ 
    [AuthorizationFilter]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/DeletesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class DeletesController : Controller
    {
        // GET: Deletes
        public ActionResult Admin()
        {
            return View();
        }

        // GET: Deletes
        public ActionResult Regular()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/PCollegesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using clinic_management.Models;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class PCollegesController : Controller
    {
        private dbClinicManagementEntities db = new dbClinicManagementEntities();

        // GET: PColleges
        public ActionResult Index()
        {
            return View(db.PColleges.ToList().Where(pc => pc.deleted == "0"));
        }

        // GET: PColleges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PCollege pCollege = db.PColleges.Find(id);
            if (pCollege == null)
            {
                return HttpNotFound();
            }
            return View(pCollege);
        }

        // GET: PColleges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PColleges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CollegeID,CollegeCode,CollegeName,deleted")] PCollege pCollege)
        {
            if (ModelState.IsValid)
            {
                pCollege.deleted = "0";
                db.PColleges.Add(pCollege);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pCollege);
        }

        // GET: PColleges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PCollege pCollege = db.PColleges.Find(id);
            if (pCollege == null)
            {
                return HttpNotFound();
            }
            return View(pCollege);
        }

        // POST: PColleges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CollegeID,CollegeCode,CollegeName,deleted")] PCollege pCollege)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pCollege).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pCollege);
        }

        // GET: PColleges/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PCollege pCollege = db.PColleges.Find(id);
            if (pCollege == null)
            {
                return HttpNotFound();
            }
            return View(pCollege);
        }

        // POST: PColleges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //PCollege pCollege = db.PColleges.Find(id);
            //db.PColleges.Remove(pCollege);
            //db.SaveChanges();

            var result = db.PColleges.SingleOrDefault(pc => pc.CollegeID == id);
            if (result != null)
            {
                result.deleted = "1";
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: PatientTypes/Recover
        public ActionResult Recover(int? id)
        {
            if (id == null)
            {
                return View(db.PColleges.ToList().Where(pc => pc.deleted == "1"));
            }

            var result = db.PColleges.SingleOrDefault(pc => pc.CollegeID == id);
            if (result != null)
            {
                result.deleted = "0";
                db.SaveChanges();
            }

            return View(db.PColleges.ToList().Where(pc => pc.deleted == "1"));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

clinic-management/clinic-management/Views/PColleges/Create.cshtml
@model clinic_management.Models.PCollege

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Colleges</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CollegeCode, "College Code", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.CollegeCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegeCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CollegeName,"College Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.CollegeName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

clinic-management/clinic-management/Views/PColleges/Delete.cshtml
@model clinic_management.Models.PCollege

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Colleges</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <label> Are you sure you want to delete this?</label>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CollegeCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CollegeCode)
            </dd>

            <dt>
                @Html.Label("College Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CollegeName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

clinic-management/clinic-management/Views/PColleges/Details.cshtml
@model clinic_management.Models.PCollege

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Colleges</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CollegeCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CollegeCode)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CollegeName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CollegeName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.CollegeID, @class = "btn btn-default" })
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
    </p>
</div>

clinic-management/clinic-management/Views/PColleges/Edit.cshtml
@model clinic_management.Models.PCollege

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Colleges</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CollegeID)

            <div class="form-group">
                @Html.LabelFor(model => model.CollegeCode, "College Code", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.CollegeCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegeCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("College Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.CollegeName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="display: none;">
                @Html.LabelFor(model => model.deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.deleted, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.deleted, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

clinic-management/clinic-management/Views/PColleges/Index.cshtml
@model IEnumerable<clinic_management.Models.PCollege>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Colleges @Html.ActionLink("Create New", "Create", "PColleges", null, new { @class = "btn btn-default pull-right" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatientColleges">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("College Code")
                </th>
                <th>
                    @Html.DisplayName("College Name")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CollegeCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CollegeName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.CollegeID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.CollegeID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tablePatientColleges').DataTable();
    });
</script>

clinic-management/clinic-management/Views/PColleges/Recover.cshtml
@model IEnumerable<clinic_management.Models.PCollege>

@{
    ViewBag.Title = "Recover";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Recover @Html.ActionLink("Back", "Admin", "Deletes", null, new { @class = "btn btn-default pull-right col-md-1" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatientColleges">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("College Code")
                </th>
                <th>
                    @Html.DisplayName("College Name")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CollegeCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CollegeName)
                    </td>
                    <td>
                        @Html.ActionLink("Recover", "Recover", new { id = item.CollegeID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tablePatientColleges').DataTable();
    });
</script>