clinic-management/clinic-management/Models/Patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.MedCheckHeaders = new HashSet<MedCheck>();
        }
    
        public int PatientID { get; set; }
        public string PatientLast { get; set; }
        public string PatientFirst { get; set; }
        public string PatientMid { get; set; }
        public string PatientGender { get; set; }
        public Nullable<System.DateTime> PatientBDate { get; set; }
        public string PatientAddrss { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string PatientClass { get; set; }
        public int CollegeID { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheck> MedCheckHeaders { get; set; }
        public virtual PatientType PatientType { get; set; }
        public virtual PCollege PCollege { get; set; }
    }
}

clinic-management/clinic-management/Models/PatientType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientType()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}

clinic-management/clinic-management/Controllers/DeletesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class DeletesController : Controller
    {
        // GET: Deletes
        public ActionResult Admin()
        {
            return View();
        }

        // GET: Deletes
        public ActionResult Regular()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using clinic_management.Models;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class PatientsController : Controller
    {
        private dbClinicManagementEntities db = new dbClinicManagementEntities();

        // GET: Patients
        public ActionResult Index()
        {
            var patients = db.Patients.Include(p => p.PatientType).Include(p => p.PCollege).Where(p => p.deleted == "0");
            return View(patients.ToList());
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            ViewBag.TypeID = new SelectList(db.PatientTypes, "TypeID", "TypeName");
            ViewBag.CollegeID = new SelectList(db.PColleges, "CollegeID", "CollegeName");
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PatientID,PatientLast,PatientFirst,PatientMid,PatientGender,PatientBDate,PatientAddrss,TypeID,PatientClass,CollegeID")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.deleted = "0";
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TypeID = new SelectList(db.PatientTypes, "TypeID", "TypeName", patient.TypeID);
            ViewBag.CollegeID = new SelectList(db.PColleges, "CollegeID", "CollegeCode", patient.CollegeID);
            return View(patient);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeID = new SelectList(db.PatientTypes, "TypeID", "TypeName", patient.TypeID);
            ViewBag.CollegeID = new SelectList(db.PColleges, "CollegeID", "CollegeName", patient.CollegeID);
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PatientID,PatientLast,PatientFirst,PatientMid,PatientGender,PatientBDate,PatientAddrss,TypeID,PatientClass,CollegeID,deleted")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(db.PatientTypes, "TypeID", "TypeName", patient.TypeID);
            ViewBag.CollegeID = new SelectList(db.PColleges, "CollegeID", "CollegeCode", patient.CollegeID);
            return View(patient);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Patient patient = db.Patients.Find(id);
            //db.Patients.Remove(patient);
            //db.SaveChanges();

            var result = db.Patients.SingleOrDefault(ut => ut.PatientID == id);
            if (result != null)
            {
                result.deleted = "1";
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: PatientTypes/Recover
        public ActionResult Recover(int? id)
        {
            if (id == null)
            {
                return View(db.Patients.ToList().Where(p => p.deleted == "1"));
            }

            var result = db.Patients.SingleOrDefault(p => p.PatientID == id);
            if (result != null)
            {
                result.deleted = "0";
                db.SaveChanges();
            }

            return View(db.Patients.ToList().Where(p => p.deleted == "1"));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

clinic-management/clinic-management/Views/Patients/Create.cshtml
@model clinic_management.Models.Patient

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patients</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.PatientType, "Patient Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientFirst, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PatientFirst, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientFirst, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientMid, "Middle Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PatientMid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientMid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientLast, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PatientLast, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientLast, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientGender, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input type="radio" name="gender" value="Female" id="gender_female" onchange="setGender(this)" /> Female
                    <br />
                    <input type="radio" name="gender" value="Male" id="gender_male" onchange="setGender(this)" /> Male
                    @Html.EditorFor(model => model.PatientGender, new { htmlAttributes = new { @class = "form-control", style = "display: none;" } })
                    @Html.ValidationMessageFor(model => model.PatientGender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientBDate, "Birthdate", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <div class="input-group date" data-date-format="dd.mm.yyyy">
                        @Html.EditorFor(model => model.PatientBDate, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(model => model.PatientBDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <script>
                $(function () {
                    $('.input-group.date').datepicker({
                        format: 'yyyy-mm-dd',
                        autoclose: true
                    });
                });
            </script>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientAddrss, "Address", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PatientAddrss, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientAddrss, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PCollege, "College", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("CollegeID", null, htmlAttributes: new { @class = "js-example-basic-single form-control" })
                    @Html.ValidationMessageFor(model => model.CollegeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <script>
                $(document).ready(function () {
                    $('.js-example-basic-single').select2({
                        placeholder: "Select College",
                        allowClear: true
                    });

                    $('#CollegeID').val(null).trigger('change');
                });
            </script>

            <div class="form-group">
                @Html.LabelFor(model => model.PatientClass, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PatientClass, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientClass, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    function setGender(radio_button) {
        $('#PatientGender').val(radio_button.value);
    }
</script>

clinic-management/clinic-management/Views/Patients/Delete.cshtml
@model clinic_management.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patients</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <label>Are you sure you want to delete this?</label>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Patient Type")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientType.TypeName)
            </dd>

            <dt>
                @Html.DisplayName("First Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientFirst)
            </dd>

            <dt>
                @Html.DisplayName("Middle Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientMid)
            </dd>

            <dt>
                @Html.DisplayName("Last Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientLast)
            </dd>

            <dt>
                @Html.DisplayName("Gender")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientGender)
            </dd>

            <dt>
                @Html.DisplayName("Birthdate")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientBDate)
            </dd>

            <dt>
                @Html.DisplayName("Address")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientAddrss)
            </dd>

            <dt>
                @Html.DisplayName("College")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PCollege.CollegeName)
            </dd>
            <dt>
                @Html.DisplayName("Class")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientClass)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

clinic-management/clinic-management/Views/Patients/Details.cshtml
@model clinic_management.Models.Patient

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patients</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Patient Type")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientType.TypeName)
            </dd>
            <dt>
                @Html.DisplayName("Last Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientLast)
            </dd>

            <dt>
                @Html.DisplayName("First Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientFirst)
            </dd>

            <dt>
                @Html.DisplayName("Middle Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientMid)
            </dd>

            <dt>
                @Html.DisplayName("Gender")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientGender)
            </dd>

            <dt>
                @Html.DisplayName("Birthdate")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientBDate)
            </dd>

            <dt>
                @Html.DisplayName("Address")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientAddrss)
            </dd>

            <dt>
                @Html.DisplayName("College")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PCollege.CollegeName)
            </dd>

            <dt>
                @Html.DisplayName("Class")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientClass)
            </dd>
        </dl>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Update", "Edit", "Patients", new { id = Model.PatientID },new { @class = "btn btn-default" })
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>

clinic-management/clinic-management/Views/Patients/Edit.cshtml
@model clinic_management.Models.Patient

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Update Patient Information</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PatientID)

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "Patient Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientFirst, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PatientFirst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientFirst, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientMid, "Middle Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PatientMid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientMid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientLast, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PatientLast, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientLast, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientGender, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <input type="radio" name="gender" value="Female" id="gender_female" onchange="setGender(this)" /> Female
                <br />
                <input type="radio" name="gender" value="Male" id="gender_male" onchange="setGender(this)" /> Male
                @Html.EditorFor(model => model.PatientGender, new { htmlAttributes = new { @class = "form-control", style = "display: none;" } })
                @Html.ValidationMessageFor(model => model.PatientGender, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (Model.PatientGender == "Female")
        {
            <script>
                    $('#gender_female').attr('checked', true);
            </script>
        }
        else
        {
            <script>
                    $('#gender_male').attr('checked', true);
            </script>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.PatientBDate, "Birthdate", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <div class="input-group date" data-date-format="dd.mm.yyyy">
                    @Html.EditorFor(model => model.PatientBDate, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.PatientBDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <script>
                $(function () {
                    $('.input-group.date').datepicker({
                        format: 'yyyy-mm-dd',
                        autoclose: true
                    });
                });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientAddrss, "Address", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PatientAddrss, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientAddrss, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.PatientClass, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.PatientClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollegeID, "College", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("CollegeID", null, htmlAttributes: new { @class = "js-example-basic-single form-control" })
                @Html.ValidationMessageFor(model => model.CollegeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <script>
                $(document).ready(function () {
                    $('.js-example-basic-single').select2({
                        placeholder: "Select College",
                        allowClear: true
                    });
                });
        </script>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.deleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.deleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>

    </div>

}

clinic-management/clinic-management/Views/Patients/Index.cshtml
@model IEnumerable<clinic_management.Models.Patient>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patients @Html.ActionLink("Create New", "Create", "Patients", null, new { @class = "btn btn-default pull-right" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatients">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Patient Name")
                </th>
                <th>
                    @Html.DisplayName("Gender")
                </th>
                <th>
                    @Html.DisplayName("Address")
                </th>
                <th>
                    @Html.DisplayName("Patient Type")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientFirst) @Html.DisplayFor(modelItem => item.PatientLast)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientGender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientAddrss)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientType.TypeName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.PatientID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.PatientID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.PatientID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tablePatients').DataTable();
    });
</script>

clinic-management/clinic-management/Views/Patients/Recover.cshtml
@model IEnumerable<clinic_management.Models.Patient>

@{
    ViewBag.Title = "Recover";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Recover @Html.ActionLink("Back", "Regular", "Deletes", null, new { @class = "btn btn-default pull-right" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatients">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PatientID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientLast)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientFirst)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientMid)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientLast)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientFirst)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientMid)
                    </td>
                    <td>
                        @Html.ActionLink("Recover", "Recover", new { id = item.PatientID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tablePatients').DataTable();
    });
</script>