clinic-management/clinic-management/Models/Staff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.MedCheckHeaders = new HashSet<MedCheck>();
        }
    
        public string StaffID { get; set; }
        public string StaffLast { get; set; }
        public string StaffFirst { get; set; }
        public string StaffMid { get; set; }
        public string StaffGender { get; set; }
        public string StaffPassword { get; set; }
        public Nullable<System.DateTime> StaffJoinedDate { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheck> MedCheckHeaders { get; set; }
        public virtual UserType UserType { get; set; }
    }
}

clinic-management/clinic-management/Controllers/DeletesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class DeletesController : Controller
    {
        // GET: Deletes
        public ActionResult Admin()
        {
            return View();
        }

        // GET: Deletes
        public ActionResult Regular()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using clinic_management.Models;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class StaffsController : Controller
    {
        private dbClinicManagementEntities db = new dbClinicManagementEntities();

        // GET: Staffs
        public ActionResult Index()
        {
            var staffs = db.Staffs.Include(s => s.UserType).Where(s => s.deleted == "0");
            return View(staffs.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            var intAdminCount = db.Staffs.Where(s => s.UserType.TypeDesc == "Admin").Count();
            ViewBag.AdminID = GetID("AD", intAdminCount);

            var intNurseCount = db.Staffs.Where(s => s.UserType.TypeDesc == "Nurse").Count();
            ViewBag.NurseID = GetID("NS", intNurseCount);

            var intDoctorCount = db.Staffs.Where(s => s.UserType.TypeDesc == "Doctor").Count();
            ViewBag.DoctorID = GetID("DC", intDoctorCount);

            var intReceptionistCount = db.Staffs.Where(s => s.UserType.TypeDesc == "Receptionist").Count();
            ViewBag.ReceptionistID = GetID("NR", intReceptionistCount);

            ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "TypeDesc");
            return View();
        }

        public string GetID(string format, int count)
        {
            string id = format;
            int idCount = count + 1;

            for(int i = idCount.ToString().Count(); i < 4; i++)
            {
                id += '0';
            }

            return id + idCount;
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffID,StaffLast,StaffFirst,StaffMid,StaffGender,StaffPassword,StaffJoinedDate,UserTypeID")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                staff.deleted = "0";
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "TypeDesc", staff.UserTypeID);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "TypeDesc", staff.UserTypeID);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StaffID,StaffLast,StaffFirst,StaffMid,StaffGender,StaffPassword,StaffJoinedDate,UserTypeID,deleted")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "TypeDesc", staff.UserTypeID);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            //Staff staff = db.Staffs.Find(id);
            //db.Staffs.Remove(staff);
            //db.SaveChanges();

            var result = db.Staffs.SingleOrDefault(s => s.StaffID == id);
            if (result != null)
            {
                result.deleted = "1";
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Staffs/ChangePassword
        public ActionResult ChangePassword(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword([Bind(Include = "StaffID,StaffPassword")] Staff staff, string confirm_password)
        {
            if (staff.StaffPassword == confirm_password)
            {
                var result = db.Staffs.SingleOrDefault(s => s.StaffID == staff.StaffID);
                if (result != null)
                {
                    result.StaffPassword = confirm_password;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrorMessage = "Passwords do not match";
                ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "TypeDesc", staff.UserTypeID);
                return View(staff);
            }
        }

        // GET: PatientTypes/Recover
        public ActionResult Recover(string id)
        {
            if (id == null)
            {
                return View(db.Staffs.ToList().Where(s => s.deleted == "1"));
            }

            var result = db.Staffs.SingleOrDefault(s => s.StaffID == id);
            if (result != null)
            {
                result.deleted = "0";
                db.SaveChanges();
            }

            return View(db.Staffs.ToList().Where(s => s.deleted == "1"));
        }
    }
}

clinic-management/clinic-management/Views/Staffs/ChangePassword.cshtml
@model clinic_management.Models.Staff

@{
    ViewBag.Title = "ChangePassword";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.StaffID)

            <div class="form-group">
                @Html.LabelFor(model => model.StaffPassword, "New Password", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffPassword, new { htmlAttributes = new { @class = "form-control", type = "password", @Value = "" } })
                    @Html.ValidationMessageFor(model => model.StaffPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Confirm Password</label>
                <div class="col-md-5">
                    <input type="password" class="form-control" name="confirm_password" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <span class="field-validation-valid text-danger" data-valmsg-replace="true">@ViewBag.ErrorMessage</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

clinic-management/clinic-management/Views/Staffs/Create.cshtml
@model clinic_management.Models.Staff

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserTypeID, "User Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("UserTypeID", null, htmlAttributes: new { @class = "form-control", onchange = "SetID()" })
                    @Html.ValidationMessageFor(model => model.UserTypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffID, "Staff ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffFirst, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffFirst, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffFirst, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffMid, "Middle Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffMid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffMid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffLast, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffLast, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffLast, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffGender, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input type="radio" name="gender" value="Female" id="gender_female" onchange="setGender(this)" /> Female
                    <br />
                    <input type="radio" name="gender" value="Male" id="gender_male" onchange="setGender(this)" /> Male
                    @Html.EditorFor(model => model.StaffGender, new { htmlAttributes = new { @class = "form-control", style = "display: none;" } })
                    @Html.ValidationMessageFor(model => model.StaffGender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffPassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffPassword, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                    @Html.ValidationMessageFor(model => model.StaffPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffJoinedDate, "Date of Joined", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <div class="input-group date" data-date-format="dd.mm.yyyy">
                        @Html.EditorFor(model => model.StaffJoinedDate, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(model => model.StaffJoinedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <script>
                $(function () {
                    $('.input-group.date').datepicker({
                        format: 'yyyy-mm-dd',
                        autoclose:true
                    });
                });
            </script>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        SetID();
    });

    function setGender(radio_button) {
        $('#StaffGender').val(radio_button.value);
    }

    function SetID() {
        var e = document.getElementById("UserTypeID");
        var strUserType = e.options[e.selectedIndex].text;

        if (strUserType == "Admin") {

            $('#StaffID').val('@ViewBag.AdminID');

        } else if (strUserType == "Nurse") {

            $('#StaffID').val('@ViewBag.NurseID');

        } else if (strUserType == "Doctor") {

            $('#StaffID').val('@ViewBag.DoctorID');

        } else if (strUserType == "Receptionist") {

            $('#StaffID').val('@ViewBag.ReceptionistID');

        }
    }
</script>

clinic-management/clinic-management/Views/Staffs/Delete.cshtml
@model clinic_management.Models.Staff

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <label>Are you sure you want to delete this?</label>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StaffLast)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffLast)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StaffFirst)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffFirst)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StaffMid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffMid)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StaffGender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffGender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StaffPassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffPassword)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StaffJoinedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StaffJoinedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserType.TypeDesc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserType.TypeDesc)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

clinic-management/clinic-management/Views/Staffs/Details.cshtml
@model clinic_management.Models.Staff

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

    <div class="row">
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayName("First Name")
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.StaffFirst)
                </dd>

                <dt>
                    @Html.DisplayName("Middle Name")
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.StaffMid)
                </dd>

                <dt>
                    @Html.DisplayName("Last Name")
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.StaffLast)
                </dd>

                <dt>
                    @Html.DisplayName("Gender")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StaffGender)
                </dd>

                <dt>
                    @Html.DisplayName("Password")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StaffPassword)
                </dd>

                <dt>
                    @Html.DisplayName("Date of Joined")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StaffJoinedDate)
                </dd>

                <dt>
                    @Html.DisplayName("User")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserType.TypeDesc)
                </dd>
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </dl>
        </div>
    </div>

clinic-management/clinic-management/Views/Staffs/Edit.cshtml
@model clinic_management.Models.Staff

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.StaffID)

            <div class="form-group">
                @Html.LabelFor(model => model.UserTypeID, "User Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("UserTypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserTypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffFirst, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffFirst, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffFirst, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffMid, "Middle Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffMid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffMid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffLast, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffLast, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffLast, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffGender, "Gender",  htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input type="radio" name="gender" value="Female" id="gender_female" onchange="setGender(this)" /> Female
                    <br />
                    <input type="radio" name="gender" value="Male" id="gender_male" onchange="setGender(this)" /> Male
                    @Html.EditorFor(model => model.StaffGender, new { htmlAttributes = new { @class = "form-control", style = "display: none;" } })
                    @Html.ValidationMessageFor(model => model.StaffGender, "", new { @class = "text-danger" })
                </div>
            </div>

            @if (Model.StaffGender == "Female")
            {
                <script>
                    $('#gender_female').attr('checked', true);
                </script>
            }
            else
            {
                <script>
                    $('#gender_male').attr('checked', true);
                </script>
            }

            <div class="form-group" style="display: none;">
                @Html.LabelFor(model => model.StaffPassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StaffPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffJoinedDate, "Date of Joined", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <div class="input-group date" data-date-format="dd.mm.yyyy">
                        @Html.EditorFor(model => model.StaffJoinedDate, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(model => model.StaffJoinedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <script>
                $(function () {
                    $('.input-group.date').datepicker({
                        format: 'yyyy-mm-dd',
                        autoclose:true
                    });
                });
            </script>

            <div class="form-group" style="display: none;">
                @Html.LabelFor(model => model.deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.deleted, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.deleted, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    function setGender(radio_button) {
        $('#StaffGender').val(radio_button.value);
    }
</script>

clinic-management/clinic-management/Views/Staffs/Index.cshtml
@model IEnumerable<clinic_management.Models.Staff>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Accounts @Html.ActionLink("Register a Staff", "Create", "Staffs", null, new { @class = "btn btn-default pull-right" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tableUser">
        <thead>
            <tr>
                <th>
                    @Html.Label("Staff Name")
                </th>
                <th>
                    @Html.Label("Gender")
                </th>
                <th>
                    @Html.Label("Joined Date")
                </th>
                <th>
                    @Html.Label("User Type")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffFirst) @Html.DisplayFor(modelItem => item.StaffLast)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffGender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffJoinedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserType.TypeDesc)
                    </td>
                    <td>
                        @Html.ActionLink("Change Password", "ChangePassword", new { id = item.StaffID }) |
                        @Html.ActionLink("Edit", "Edit", new { id = item.StaffID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.StaffID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.StaffID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tableUser').DataTable();
    });
</script>

clinic-management/clinic-management/Views/Staffs/Recover.cshtml
@model IEnumerable<clinic_management.Models.Staff>

@{
    ViewBag.Title = "Recover";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Recover @Html.ActionLink("Back", "Admin", "Deletes", null, new { @class = "btn btn-default pull-right col-md-1" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tableStaffs">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Staff ID")
                </th>
                <th>
                    @Html.DisplayName("Last Name")
                </th>
                <th>
                    @Html.DisplayName("First Name")
                </th>
                <th>
                    @Html.DisplayName("Middle Name")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffLast)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffFirst)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StaffMid)
                    </td>
                    <td>
                        @Html.ActionLink("Recover", "Recover", new { id = item.StaffID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tableStaffs').DataTable();
    });
</script>