clinic-management/clinic-management/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{ 
    [AuthorizationFilter]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/DeletesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class DeletesController : Controller
    {
        // GET: Deletes
        public ActionResult Admin()
        {
            return View();
        }

        // GET: Deletes
        public ActionResult Regular()
        {
            return View();
        }
    }
}

clinic-management/clinic-management/Controllers/PatientTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using clinic_management.Models;
using static clinic_management.Helpers.Sessions;

namespace clinic_management.Controllers
{
    [AuthorizationFilter]
    public class PatientTypesController : Controller
    {
        private dbClinicManagementEntities db = new dbClinicManagementEntities();

        // GET: PatientTypes
        public ActionResult Index()
        {
            return View(db.PatientTypes.ToList().Where(pt => pt.deleted == "0"));
        }

        // GET: PatientTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientType patientType = db.PatientTypes.Find(id);
            if (patientType == null)
            {
                return HttpNotFound();
            }
            return View(patientType);
        }

        // GET: PatientTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeID,TypeName,deleted")] PatientType patientType)
        {
            if (ModelState.IsValid)
            {
                patientType.deleted = "0";
                db.PatientTypes.Add(patientType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patientType);
        }

        // GET: PatientTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientType patientType = db.PatientTypes.Find(id);
            if (patientType == null)
            {
                return HttpNotFound();
            }
            return View(patientType);
        }

        // POST: PatientTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeID,TypeName,deleted")] PatientType patientType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patientType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patientType);
        }

        // GET: PatientTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientType patientType = db.PatientTypes.Find(id);
            if (patientType == null)
            {
                return HttpNotFound();
            }
            return View(patientType);
        }

        // POST: PatientTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //PatientType patientType = db.PatientTypes.Find(id);
            //db.PatientTypes.Remove(patientType);
            //db.SaveChanges();

            var result = db.PatientTypes.SingleOrDefault(pt => pt.TypeID == id);
            if (result != null)
            {
                result.deleted = "1";
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: PatientTypes/Recover
        public ActionResult Recover(int? id)
        {
            if (id == null)
            {
                return View(db.PatientTypes.ToList().Where(pt => pt.deleted == "1"));
            }

            var result = db.PatientTypes.SingleOrDefault(pt => pt.TypeID == id);
            if (result != null)
            {
                result.deleted = "0";
                db.SaveChanges();
            }

            return View(db.PatientTypes.ToList().Where(pt => pt.deleted == "1"));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

clinic-management/clinic-management/Views/PatientTypes/Create.cshtml
@model clinic_management.Models.PatientType

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Types</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TypeName, "Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

clinic-management/clinic-management/Views/PatientTypes/Delete.cshtml
@model clinic_management.Models.PatientType

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Types</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div>
        <label>Are you sure you want to delete this?</label>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Type Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TypeName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

clinic-management/clinic-management/Views/PatientTypes/Details.cshtml
@model clinic_management.Models.PatientType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PatientType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deleted)
        </dd>

    </dl>
    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
</div>

clinic-management/clinic-management/Views/PatientTypes/Edit.cshtml
@model clinic_management.Models.PatientType

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Types</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.TypeID)

            <div class="form-group">
                @Html.LabelFor(model => model.TypeName, "Type Name",htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="display: none;">
                @Html.LabelFor(model => model.deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.deleted, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.deleted, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }
</div>

clinic-management/clinic-management/Views/PatientTypes/Index.cshtml
@model IEnumerable<clinic_management.Models.PatientType>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Patient Types @Html.ActionLink("Create New", "Create", "PatientTypes", null, new { @class = "btn btn-default pull-right" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatientTypes">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Type Name")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="center-block">
                        @Html.DisplayFor(modelItem => item.TypeName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.TypeID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.TypeID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        $('#tablePatientTypes').DataTable();
    });
</script>

clinic-management/clinic-management/Views/PatientTypes/Recover.cshtml
@model IEnumerable<clinic_management.Models.PatientType>

@{
    ViewBag.Title = "Recover";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Recover @Html.ActionLink("Back", "Admin", "Deletes", null, new { @class = "btn btn-default pull-right col-md-1" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <table class="table" id="tablePatientTypes">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Type Name")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeName)
                    </td>
                    <td>
                        @Html.ActionLink("Recover", "Recover", new { id = item.TypeID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tablePatientTypes').DataTable();
    });
</script>